#!/bin/bash
set -e

echo "🚀 Starting Deployment Pipeline..."

# 1. Setup Infrastructure
echo "Step 1: Provisioning Infrastructure..."
chmod +x setup_gcp_resources.sh
./setup_gcp_resources.sh

# Load configurations
PROJECT_ID=$(gcloud config get-value project)
REGION="asia-south1" # Standardizing region to match previous found logs
# Or better, read from gcloud default or ask user. 
# The setup script used us-central1. I should probably respect that or match existing services.
# The user's existing failed service 'wedding-backend' was in 'asia-south1' (step 217).
# I should probably use asia-south1 to keep it close to user/existing resources.
# BUT setup_gcp_resources.sh had REGION="us-central1" hardcoded (step 202). 
# If I already ran it (I didn't fully yet), it might create in us-central1.
# I'll force asia-south1 in this script if I can, or update setup script. 
# Actually, let's update setup script to match asia-south1 if that's where their other stuff is.
# For now, I'll trust the setup script output for variables.

# Extract variables from setup script logic or output file
# It's cleaner to read the db_password.txt generated by setup script
if [ ! -f db_password.txt ]; then
    echo "❌ Error: db_password.txt not found. Infrastructure setup might have failed."
    exit 1
fi
DB_PASSWORD=$(cat db_password.txt)
DB_USER="wedding_user"
DB_NAME="wedding_web"
SQL_INSTANCE_NAME="wedding-web-db"
BUCKET_NAME="wedding-web-photos-${PROJECT_ID}"

# Get the connection name
INSTANCE_CONNECTION_NAME=$(gcloud sql instances describe $SQL_INSTANCE_NAME --format="value(connectionName)" --quiet)

echo "✅ Infrastructure Ready."
echo "   DB Connection: $INSTANCE_CONNECTION_NAME"
echo "   Bucket: $BUCKET_NAME"

# 2. Build Backend Container
echo "Step 2: Building Backend Container..."
cd backend
# Submit build to Cloud Build
gcloud builds submit --tag gcr.io/$PROJECT_ID/wedding-backend . --quiet

# 3. Deploy to Cloud Run
echo "Step 3: Deploying to Cloud Run..."
gcloud run deploy wedding-backend \
    --image gcr.io/$PROJECT_ID/wedding-backend \
    --platform managed \
    --region asia-south1 \
    --allow-unauthenticated \
    --set-env-vars="DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,DB_NAME=$DB_NAME,DB_HOST=/cloudsql/$INSTANCE_CONNECTION_NAME,GCS_BUCKET_NAME=$BUCKET_NAME,NODE_ENV=production,SUPABASE_URL=REMOVED,SUPABASE_ANON_KEY=REMOVED" \
    --add-cloudsql-instances=$INSTANCE_CONNECTION_NAME \
    --quiet

echo "🎉 Deployment Complete!"
SERVICE_URL=$(gcloud run services describe wedding-backend --platform managed --region asia-south1 --format="value(status.url)" --quiet)
echo "🌍 Service URL: $SERVICE_URL"
