services:
  - type: web
    name: wedding-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    region: oregon # Or your preferred region
    branch: main # Or your deployment branch
    envVars:
      - key: PORT
        fromValue: PORT # Render will inject the dynamic port
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
